Add the DFS and BFS traversal algorithms
ba-st/Mole pull request #13
Opened 2018-12-24 19:07 UTC by jvanecek

A straightforward implementations of the algorithms to solve the issues #7 and #8

2018-12-26 18:53 UTC, fortizpenaloza requested changes
Improve the docs on https://github.com/ba-st/Mole/blob/master/docs/Mole.md to reflect the changes

2018-12-26 19:05 UTC, fortizpenaloza requested changes

2018-12-26 19:05 UTC, fortizpenaloza commented on source/Mole/DirectedGraph.class.st
> +		collect: [ :directedEdge | directedEdge target ]
```smalltalk
^ (self edgesOutgoingFrom: aSourceVertex) collect: #target
```

2018-12-26 19:05 UTC, fortizpenaloza commented on source/Mole/UndirectedGraph.class.st
> +]
Can be changed to a simpler collaboration using #reject: ?

2019-01-06 15:18 UTC, jvanecek commented on source/Mole-Tests/GraphTraversalAlgorithmTest.class.st
> +GraphTraversalAlgorithmTest >> directedGraph [
Glad you suggested it as it let me fix a bug in BFS with loops in vertices

2019-01-24 18:34 UTC, gcotelli approved these changes

2019-01-24 19:13 UTC, merged